/* ============================================================================
   PATCH - EMPRESAS DE TRANSPORTE (ETR)
   Fuente: listado ETR_COD / ETR_DENOMIN / ETR_NOMBRE
   Regla: no duplicar registros existentes.
============================================================================ */
SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRANSACTION;

DECLARE @now DATETIME2(0) = SYSDATETIME();

IF OBJECT_ID('tempdb..#etr_src') IS NOT NULL
  DROP TABLE #etr_src;

CREATE TABLE #etr_src (
  etr_cod CHAR(3) NOT NULL PRIMARY KEY,
  etr_denomin VARCHAR(100) NOT NULL,
  etr_nombre VARCHAR(100) NOT NULL
);

INSERT INTO #etr_src (etr_cod, etr_denomin, etr_nombre)
VALUES
('001', N'SERTCHILE LTA', N'SERTCHILE LTA'),
('002', N'TRANSPORTE AZOCAR', N'TRANSPORTE AZOCAR'),
('003', N'TRANSPORTE CASTILLO', N'TRANSPORTE CASTILLO'),
('004', N'TRANSP.MORROS', N'TRANSPORTES MORROS'),
('005', N'TRANSPORTE SPT', N'TRANSPORTE SPT'),
('006', N'TRANSPORTE M.D.', N'TRANSPORTE M.D.'),
('007', N'HECTOR M. SOTO V.', N'HECTOR M. SOTO V.'),
('008', N'JORQUERA TRANPOSTE', N'JORQUERA TRANPOSTE'),
('009', N'MARIO ROLANDO ZE.', N'MARIO ROLANDO ZE.'),
('010', N'TRANSP. DEL SOL LT', N'TRANSP. DEL SOL LT'),
('011', N'TRANSPORTE ALIVAL', N'TRANSPORTE ALIVAL'),
('012', N'TRANSPORTE BUEN', N'TRANSPORTE BUEN'),
('013', N'TRANSPORTE CATA', N'TRANSPORTE CATA'),
('014', N'TRANSPORTE LOGI.', N'TRANSPORTE LOGI.'),
('015', N'TRANSPORTE SAN.', N'TRANSPORTE SAN.'),
('016', N'TRANSPORTE VOLG.', N'TRANSPORTE VOLG.'),
('017', N'TRANSP. CASTELLINI', N'TRANSP. CASTELLINI'),
('018', N'PARTICULAR', N'PARTICULAR'),
('019', N'SILVESTRIN', N'SILVESTRIN'),
('020', N'GTM', N'GTM'),
('021', N'TLI TRANSPORTES S.A.', N'TLI TRANSPORTESS.A.C'),
('022', N'TRANSPORTES MERIDIAN', N'TRANSPORTES MERIDIAN'),
('023', N'TRANSPORTES MAERSK', N'TRANSPORTES MAERSK'),
('024', N'TRANSPORTES NIZA', N'TRANSPORTES NIZA'),
('025', N'TRANSP. JORGE GUERRA', N'TRANSP. JORGE GUERRA'),
('026', N'CARLOS VILLAGRAN', N'CARLOS VILLAGRAN'),
('027', N'CENTRO LOG. CASTELLI', N'CENTRO LOG. CASTELLI'),
('028', N'TRANSPORTES GUAJARDO', N'TRANSPORTES GUAJARDO'),
('029', N'POR ASIGNAR', N'POR ASIGNAR'),
('600', N'ALEXIS OSSES', N'ALEXIS OSSES'),
('601', N'ANDREA CORNEJO', N'ANDREA CORNEJO'),
('602', N'LUIS GUERRERO', N'LUIS GUERRERO'),
('603', N'JUAN DIAZ SANCHEZ', N'JUAN DIAZ SANCHEZ'),
('604', N'HECTOR SOTO E.I.R.L.', N'HECTOR SOTO E.I.R.L.'),
('605', N'TRUCK SERVICE SPA', N'TRUCK SERVICE SPA'),
('606', N'ARPAR SPA', N'ARPAR SPA'),
('607', N'LUIS IBAÑEZ PIZARRO', N'LUIS IBAÑEZ PIZARRO'),
('608', N'SEBASTIAN SALINAS', N'SEBASTIAN SALINAS'),
('609', N'PONCE MUÑOZ', N'PONCE MUÑOZ'),
('610', N'CRISTIAN MENESES', N'CRISTIAN MENESES'),
('611', N'JOSE LUIS OPAZO', N'JOSE LUIS OPAZO'),
('612', N'CARLA GUAJARDO', N'CARLA GUAJARDO'),
('613', N'CORPERT TRANSPORTES', N'CORPERT TRANSPORTES'),
('614', N'PEDRO URRUCELQUI', N'PEDRO URRUCELQUI'),
('615', N'ANDREA BARJA', N'ANDREA BARJA'),
('616', N'PEDRO ROMERO FARFAN', N'PEDRO ROMERO FARFAN'),
('617', N'TRANSPORTES ALIVAL', N'TRANSPORTES ALIVAL'),
('618', N'TRANS DE PRIETO', N'TRANS DE PRIETO'),
('619', N'CAROLINA CABEZAS', N'CAROLINA CABEZAS'),
('620', N'GUILLERMO PASTRIAN', N'GUILLERMO PASTRIAN'),
('621', N'TRANSP. AVILA SPA', N'TRANSP. AVILA SPA'),
('622', N'CACERES QUINTANILLA', N'CACERES QUINTANILLA'),
('623', N'JOSE NELSON CONTRERA', N'JOSE NELSON CONTRERA'),
('624', N'PABLO CONTRERAS V.', N'PABLO CONTRERAS V.'),
('625', N'CARLOS PALOMINOS', N'CARLOS PALOMINOS'),
('626', N'JOTA H MAQUINARIAS', N'JOTA H MAQUINARIAS'),
('627', N'DELFINA LAVIN', N'DELFINA LAVIN'),
('628', N'SILVIA CANALES RAMIR', N'SILVIA CANALES RAMIR'),
('629', N'FRIOAUSTRAL LTDA', N'FRIOAUSTRAL LTDA'),
('630', N'DEL VALLE CENTRAL', N'DEL VALLE CENTRAL'),
('631', N'TRANSP. UBALDO PAVEZ', N'TRANSP. UBALDO PAVEZ'),
('632', N'TRANSP. GOMEZ CACERE', N'TRANSP. GOMEZ CACER'),
('633', N'TRANSP. QUIROGA', N'TRANSP. QUIROGA'),
('634', N'INGRID DEL PILAR GOM', N'INGRID DEL PILAR GOM'),
('635', N'PARTICULAR', N'PARTICULAR'),
('636', N'TRANSP. ROMERO SPA', N'TRANSP. ROMERO SPA'),
('637', N'TRANSP. AGROMIST', N'TRANSP. AGROMIST'),
('638', N'.', N'.'),
('639', N'TRANSP. COMER IGUAZU', N'TRANSP. COMER IGUAZU'),
('640', N'TRANSP. CHIMBARONGO', N'TRANSP. CHIMBARONGO'),
('641', N'TRANSPORTES ANGA SPA', N'TRANSPORTES ANGA SPA'),
('642', N'TRANSP. LOS TRES ANT', N'TRANSP. LOS TRES ANT'),
('643', N'TRANSP. XIMENA OSORI', N'TRANSP. XIMENA OSORI'),
('644', N'TRANSP. SANTA SOFIA', N'TRANSP. SANTA SOFIA'),
('645', N'TRANSP. PIEMONTE LTD', N'TRANSP. PIEMONTE LTD'),
('646', N'TRANSP. JOSE AVILA R', N'TRANSP. JOSE AVILA R'),
('647', N'TRANSP. EL CANELO', N'TRANSP. EL CANELO'),
('648', N'TRANSP. LOS CASTAÑOS', N'TRANSP. LOS CASTAÑOS'),
('649', N'TRANSP. INV Y CONSTR', N'TRANSP. INV Y CONSTR'),
('650', N'TRANSP. C.C.G. SPA', N'TRANSP. C.C.G. SPA'),
('651', N'TRANSPORTES PATRICIO', N'TRANSP PATRICIO GUTI'),
('652', N'SOC TRANSP COMERC MU', N'SOC TRANSP COMERC MU');

/* 1) Actualiza empresas que ya existen por sap_codigo */
UPDATE t
SET
  t.razon_social = s.etr_denomin,
  t.nombre_rep = s.etr_nombre,
  t.activo = 1,
  t.updated_at = @now
FROM cfl.CFL_empresa_transporte t
INNER JOIN #etr_src s ON t.sap_codigo = s.etr_cod;

/* 2) Si existe por nombre y aun no tiene sap_codigo, lo asigna */
UPDATE t
SET
  t.sap_codigo = s.etr_cod,
  t.razon_social = s.etr_denomin,
  t.nombre_rep = s.etr_nombre,
  t.activo = 1,
  t.updated_at = @now
FROM cfl.CFL_empresa_transporte t
INNER JOIN #etr_src s
  ON UPPER(LTRIM(RTRIM(ISNULL(t.razon_social, '')))) = UPPER(LTRIM(RTRIM(s.etr_denomin)))
WHERE t.sap_codigo IS NULL
  AND NOT EXISTS (
    SELECT 1
    FROM cfl.CFL_empresa_transporte x
    WHERE x.sap_codigo = s.etr_cod
  );

/* 3) Inserta solo las que no existen por codigo ni por nombre */
INSERT INTO cfl.CFL_empresa_transporte
  (sap_codigo, rut, razon_social, nombre_rep, correo, telefono, activo, created_at, updated_at)
SELECT
  s.etr_cod,
  CONCAT('SAP-ETR-', s.etr_cod),
  s.etr_denomin,
  s.etr_nombre,
  NULL,
  NULL,
  1,
  @now,
  @now
FROM #etr_src s
WHERE NOT EXISTS (
  SELECT 1
  FROM cfl.CFL_empresa_transporte t
  WHERE t.sap_codigo = s.etr_cod
)
AND NOT EXISTS (
  SELECT 1
  FROM cfl.CFL_empresa_transporte t
  WHERE UPPER(LTRIM(RTRIM(ISNULL(t.razon_social, '')))) = UPPER(LTRIM(RTRIM(s.etr_denomin)))
);

COMMIT TRANSACTION;

DROP TABLE #etr_src;
